import { Recipe } from "@/types/recipe";

export const SEED_RECIPES: Recipe[] = [
  {
    id: "1",
    name: "红烧鸡腿",
    category: "meat",
    description: "周末必做，孩子最爱",
    ingredients: "鸡腿 2个\n生抽 1勺\n老抽 半勺\n料酒 1勺\n冰糖 适量\n姜片 3片",
    steps: "1. 鸡腿焯水去腥\n2. 煎至两面微黄\n3. 加入调料和适量水\n4. 大火烧开转小火炖煮25分钟\n5. 大火收汁",
    prepTime: "30分钟",
    notes: "少放盐，生抽已有咸味",
    createdAt: "2026-01-01",
  },
  {
    id: "2",
    name: "咖喱牛肉",
    category: "meat",
    description: "浓郁下饭，适合周末慢炖",
    ingredients: "牛腩 500g\n土豆 2个\n胡萝卜 1根\n洋葱 1个\n咖喱块 100g",
    steps: "1. 牛腩切块焯水\n2. 洋葱炒香\n3. 加入牛腩翻炒\n4. 加水没过食材\n5. 炖煮40分钟后加土豆胡萝卜\n6. 加咖喱块煮至浓稠",
    prepTime: "60分钟",
    notes: "土豆不要太早放，容易煮烂",
    createdAt: "2026-01-02",
  },
  {
    id: "3",
    name: "糖醋排骨",
    category: "meat",
    description: "酸甜可口，年夜饭必备",
    ingredients: "小排 500g\n醋 2勺\n糖 3勺\n生抽 2勺\n料酒 1勺",
    steps: "1. 排骨焯水\n2. 煎至金黄\n3. 加入糖醋汁\n4. 小火焖煮20分钟\n5. 大火收汁撒芝麻",
    prepTime: "35分钟",
    notes: "糖醋比例 3:2 最好吃",
    createdAt: "2026-01-03",
  },
  {
    id: "4",
    name: "清炒菠菜",
    category: "vegetable",
    description: "简单快速，10分钟搞定",
    ingredients: "菠菜 1把\n蒜 3瓣\n盐 适量",
    steps: "1. 菠菜洗净切段\n2. 蒜切末\n3. 热油爆香蒜末\n4. 下菠菜大火翻炒\n5. 加盐调味出锅",
    prepTime: "10分钟",
    notes: "菠菜不要炒太久，会出很多水",
    createdAt: "2026-01-04",
  },
  {
    id: "5",
    name: "番茄炒蛋",
    category: "vegetable",
    description: "家常经典，永远不会错",
    ingredients: "番茄 2个\n鸡蛋 3个\n糖 1小勺\n盐 适量\n葱花 少许",
    steps: "1. 番茄切块，鸡蛋打散\n2. 先炒鸡蛋盛出\n3. 炒番茄出汁\n4. 加入鸡蛋翻炒\n5. 加糖和盐调味",
    prepTime: "15分钟",
    notes: "加一点糖提鲜，番茄要炒出汁",
    createdAt: "2026-01-05",
  },
  {
    id: "6",
    name: "紫菜蛋花汤",
    category: "soup",
    description: "清淡暖胃，随时可做",
    ingredients: "紫菜 适量\n鸡蛋 1个\n盐 适量\n香油 几滴\n葱花 少许",
    steps: "1. 水烧开\n2. 放入紫菜\n3. 淋入蛋液\n4. 加盐和香油\n5. 撒葱花出锅",
    prepTime: "5分钟",
    notes: "蛋液要慢慢淋，才能成蛋花",
    createdAt: "2026-01-06",
  },
  {
    id: "7",
    name: "西红柿鸡蛋汤",
    category: "soup",
    description: "酸甜开胃，百搭汤品",
    ingredients: "西红柿 1个\n鸡蛋 1个\n盐 适量\n香菜 少许",
    steps: "1. 西红柿切块\n2. 水烧开放入西红柿\n3. 煮2分钟\n4. 淋入蛋液\n5. 加盐出锅撒香菜",
    prepTime: "10分钟",
    notes: "",
    createdAt: "2026-01-07",
  },
  {
    id: "8",
    name: "蛋炒饭",
    category: "staple",
    description: "消灭剩饭的最佳方式",
    ingredients: "隔夜米饭 1碗\n鸡蛋 2个\n葱花 适量\n盐 适量",
    steps: "1. 鸡蛋打散炒熟\n2. 下米饭大火翻炒\n3. 加盐调味\n4. 撒葱花出锅",
    prepTime: "10分钟",
    notes: "一定要用隔夜饭，粒粒分明",
    createdAt: "2026-01-08",
  },
  {
    id: "9",
    name: "凉拌黄瓜",
    category: "other",
    description: "夏天开胃小菜，拍一拍就好",
    ingredients: "黄瓜 2根\n蒜 3瓣\n醋 1勺\n生抽 1勺\n辣椒油 适量\n糖 少许",
    steps: "1. 黄瓜拍碎切段\n2. 蒜切末\n3. 加入所有调料\n4. 拌匀腌制10分钟",
    prepTime: "15分钟",
    notes: "拍比切好吃，更入味",
    createdAt: "2026-01-09",
  },
  {
    id: "10",
    name: "手工水饺",
    category: "staple",
    description: "全家一起包，周末的仪式感",
    ingredients: "饺子皮 500g\n猪肉馅 300g\n白菜 半颗\n姜末 适量\n生抽 2勺",
    steps: "1. 白菜切碎加盐杀水\n2. 肉馅加调料搅拌上劲\n3. 混合馅料\n4. 包饺子\n5. 水开下饺子，煮至浮起",
    prepTime: "60分钟",
    notes: "馅要顺一个方向搅，才有弹性",
    createdAt: "2026-01-10",
  },
];
